services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: unless-stopped
    ports:
      - 127.0.0.1:40831:40831
    volumes:
      - /data:/data
      - ./assets/gdam/gdam_410.gpkg:/gadm_data/gadm_410.gpkg
    
    healthcheck:
      test: curl --fail http://127.0.0.1:40831/ || exit 1
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 1m30s
      start_interval: 1s

    environment:
      BASE_DIR: /data
      PYTHONPATH: /app
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_KEY: ${SUPABASE_KEY}
      DEV_MODE: false
      GADM_DATA_PATH: /gadm_data/gadm_410.gpkg
      UVICORN_ROOT_PATH: /api/v1
      UVICORN_PORT: 40831
      UVICORN_HOST: 0.0.0.0
      LOGFIRE_TOKEN: ${LOGFIRE_TOKEN}

    # command: python run.py server --reload=False

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443

    links:
      - api
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'service', 'nginx', 'status']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1m30s
      start_interval: 1s

    volumes:
      - ./nginx/api-conf:/etc/nginx/conf.d/:ro
      - /data:/data/:ro
      - ./nginx/logs:/var/log/nginx
      - ./certbot/www:/var/www/certbot:ro
      - ./certbot/conf:/etc/nginx/ssl/:ro
  
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt:rw
    depends_on:
      - nginx
        